export * from './RouterAttendances';
export * from './RouterEvents';
export * from './RouterFaculties';
export * from './RouterHome';
export * from './RouterLogin';
export * from './RouterPersons';
export * from './RouterProfile';
export * from './RouterRoles';
export * from './RouterUsers';
